version: '3.9'
services:
  api-rest-genesis:
    container_name: api-rest-genesis
    build:
      context: .
      dockerfile: Dockerfile
    restart: always 
    depends_on:
      - mysql
    ports:
      - "8000:8000"
  mysql:
    image: mysql:8.0
    container_name: api-rest-genesis-database
    restart: always
    environment:
      MYSQL_DATABASE: mysqldatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  database: